---
name: cms-platform

services:
  redis:
    image: redis:8-alpine
    networks:
      - queue

  feed-parser:
    build:
      context: feed_parser
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    networks:
      - queue
      - db
#    command: ["-c", "tail -f /dev/null"]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feeds
    env_file:
      data/.env
    volumes:
      - /data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    networks:
      - db

networks:
  queue:
    driver: bridge
  db:
    driver: bridge

volumes:
  pg_data: